CREATE ROLE taskify_user
LOGIN
PASSWORD '45fR&2_2kv8:';

GRANT EXECUTE ON FUNCTION create_user(TEXT,TEXT,TEXT,DATE) TO taskify_user;
REVOKE ALL ON FUNCTION create_user(TEXT,TEXT,TEXT,DATE) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION get_user(TEXT) TO taskify_user;
REVOKE ALL ON FUNCTION get_user(TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION create_task(TEXT,TEXT,TEXT) TO taskify_user;
REVOKE ALL ON FUNCTION create_task(TEXT,TEXT,TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION get_tasks_by_user(TEXT) TO taskify_user;
REVOKE ALL ON FUNCTION get_tasks_by_user(TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION update_task(INTEGER,TEXT,TEXT,TEXT) TO taskify_user;
REVOKE ALL ON FUNCTION update_task(INTEGER,TEXT,TEXT,TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION delete_task(INTEGER,TEXT) TO taskify_user;
REVOKE ALL ON FUNCTION delete_task(INTEGER,TEXT) FROM PUBLIC;